### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by TonyAbell** [tpetricek/FsLab#63]
Line 57 of build.fsx

let journalPackages = 
  [ "FSharp.Compiler.Service"
    "FSharp.Formatting"
    "Microsoft.AspNet.Razor"
    "RazorEngine"
   ]
 |> List.map (fun p -> p,GetPackageVersion "packages" p)

System.Exception: Could not detect package version for Microsoft.AspNet.Razor ---> System.Exception: Package Microsoft.AspNet.Razor was not found.

When I comment out 
    "Microsoft.AspNet.Razor"
    "RazorEngine"

It builds successfully and the I amble to install and use the Template

**Comment by tpetricek** [comment]
Thanks! The two packages are no longer explicitly required (because the DLLs are included in F# Formatting), so removing them from the list is the right thing to do.

If you can send a PR with a fix, that would be awesome :-)
