### ISSUE TITLE
running R walkthrought hangs

### ISSUE THREAD

**Issue by TonyAbell** [tpetricek/FsLab#65]
src/experiments/walkthrough-with-r/Tutorial.fsx 

running within FSI works fine, however it hangs when generating html

**Comment by tpetricek** [comment]
It works on my machine :tm:!

Could you try enabling logging in R provider and check if there are any exceptions (or share the log file)? The [instructions are here](http://bluemountaincapital.github.io/FSharpRProvider/diagnostics.html).

**Comment by TonyAbell** [comment]
followed the instructions, and there was not a log file generated, and no exception was thrown.

**Comment by TonyAbell** [comment]
same issue as tpetricek/FsLab/issues/66
