### ISSUE TITLE
experiment throws exception

### ISSUE THREAD

**Issue by TonyAbell** [tpetricek/FsLab#66]
src/experiments/walkthrough/Tutorial.fsx 

Line 49 :  src/FsLab.Runner/Formatters.fs 

let vector = value.GetType().GetProperty("Vector").GetValue(value) :?> IVector

System.InvalidCastException was unhandled
Message: An unhandled exception of type 'System.InvalidCastException' occurred in FSharp.Core.dll
Additional information: Unable to cast object of type 'Deedle.Vectors.ArrayVector.ArrayVector`1[System.Double]' to type 'Deedle.IVector'.

**Comment by tpetricek** [comment]
FsLab Journal uses an odd build configuration. When built, the resulting `exe` is put into the `packages` folder and it does *not* copy any of the dependencies in there. Instead it has `config` file with `<probing>` element pointing to all the subdirectories where dependencies actually are.

The purpose of this is to make sure that the script refers to DLLs in the same location as the executable when it runs. If this is not the case, they are loaded from two different paths and so you get type cast errors like the one above.

... did you do anything to change the location of build output? (I suppose switching to Release mode could be an issue...)

**Comment by TonyAbell** [comment]
Build target is still Debug.  

Double checked and it is being run in: \packages\FsLab.Journal.exe

paket.lock

NUGET
  remote: http://nuget.org/api/v2
  specs:
    Deedle (1.0.7)
    Deedle.RPlugin (1.0.7)
      Deedle (>= 1.0.7)
      R.NET.Community (>= 1.5.16)
      R.NET.Community.FSharp (>= 0.1.9)
      RProvider (>= 1.1.8)
    Foogle.Charts (0.0.4)
    FSharp.Charting (0.90.9)
    FSharp.Compiler.Service (0.0.82)
    FSharp.Core (3.1.2.1)
    FSharp.Data (2.1.1)
      Zlib.Portable (>= 1.10.0)
    FSharp.Formatting (2.6.3)
      FSharp.Compiler.Service (>= 0.0.81)
    FsLab (0.1.3)
      Deedle (1.0.7)
      Deedle.RPlugin (1.0.7)
      FSharp.Charting (0.90.9)
      FSharp.Data (2.1.1)
      Foogle.Charts (0.0.4)
      MathNet.Numerics (3.5.0)
      MathNet.Numerics.FSharp (3.5.0)
      R.NET.Community (1.5.16)
      R.NET.Community.FSharp (0.1.9)
      RProvider (1.1.8)
    FsLab.Runner (0.1.3)
      Deedle (1.0.7)
      Deedle.RPlugin (1.0.7)
      FSharp.Charting (0.90.9)
      FSharp.Compiler.Service (0.0.82)
      FSharp.Data (2.1.1)
      FSharp.Formatting (2.6.3)
      Foogle.Charts (0.0.4)
      MathNet.Numerics (3.5.0)
      MathNet.Numerics.FSharp (3.5.0)
      Microsoft.AspNet.Razor (3.2.2)
      R.NET.Community (1.5.16)
      R.NET.Community.FSharp (0.1.9)
      RProvider (1.1.8)
      RazorEngine (3.4.2)
    MathNet.Numerics (3.5.0)
      TaskParallelLibrary (>= 1.0.2856) - >= net35 < net40
    MathNet.Numerics.FSharp (3.5.0)
      FSharp.Core (>= 3.1.2.1)
      MathNet.Numerics (3.5.0)
    Microsoft.AspNet.Razor (3.2.2)
    R.NET.Community (1.5.16)
    R.NET.Community.FSharp (0.1.9)
      R.NET.Community (>= 1.5.16)
    RazorEngine (3.4.2)
      Microsoft.AspNet.Razor (>= 3.0.0)
    RProvider (1.1.8)
      R.NET.Community (1.5.16)
      R.NET.Community.FSharp (0.1.9)
    TaskParallelLibrary (1.0.2856.0) - >= net35 < net40
    Zlib.Portable (1.10.0)

**Comment by TonyAbell** [comment]
https://onedrive.live.com/redir?resid=1384DE6278EF98D9!158949&authkey=!AFblbVTjwxwTf0Q&ithint=file%2czip

I uploaded a copy of the project.  Let me know if It Works On Your Machine.

**Comment by tpetricek** [comment]
The project you uploaded fails on my machine too.

For some reason, your project is configured to copy the dependencies into the output folder, which breaks things. If you look at the `fsproj` file, you'll see something like this (a number of times):

````xml
<When Condition="($(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.0' Or $(TargetFrameworkVersion) == 'v4.5' Or $(TargetFrameworkVersion) == 'v4.5.1' Or $(TargetFrameworkVersion) == 'v4.5.2' Or $(TargetFrameworkVersion) == 'v4.5.3')) Or ($(TargetFrameworkIdentifier) == 'MonoAndroid') Or ($(TargetFrameworkIdentifier) == 'MonoTouch')">
  <ItemGroup>
    <Reference Include="Deedle">
      <HintPath>$(MSBuildProjectDirectory)\packages\Deedle\lib\net40\Deedle.dll</HintPath>
      <Private>True</Private> <!-- Note 'Private' set to 'True' here! -->
      <Paket>True</Paket>
    </Reference>
  </ItemGroup>
</When>
````

When I create a new FsLab project on my machine, the VS leaves this as `<Private>False</Private>` and things work. 

Can you try creating a new blank project using the latest version of the template (re-install it?) to make sure that this always happens?

I'm not sure what could be changing this setting.... What VS version do you have? (I think I do not have all the VS updates installed, so that might be a difference...)

This might be related to https://github.com/fsprojects/Paket/issues/566, so perhaps we need to set the value in the template to `Never` instead of `False`...

**Comment by TonyAbell** [comment]
I am using VS 2013 Pro Update 4

I verified that when the project is created the value it set to false

 ```<Private>False</Private> ```

however when I do a paket install it value gets changed to True

**Comment by TonyAbell** [comment]
I manually changed the values ```<Private>False</Private> ``` and everything is now working even  tpetricek/FsLab/issues/65

I read through  fsprojects/Paket#566 and it was not clear what should be done.  ```Never``` does not see to be supported by VS.

**Comment by TonyAbell** [comment]
tested  changing FsLab.Journal.fsproj `<Private>Never</Private>` howerver paket still sets it to `True`

**Comment by tpetricek** [comment]
Ah, right `paket install` will overwrite this. Though you should not need to run `paket install` (all dependencies should be installed automatically when you create the project).

**Comment by TonyAbell** [comment]
when the project is created I am getting this error

```
Error	1	The command "".paket/paket.exe" restore --references-files "c:\dev\FsLab Journal8\FsLab Journal8\paket.references"" exited with code 1.	c:\dev\FsLab Journal8\FsLab Journal8\FsLab Journal8.fsproj	385	5	FsLab Journal8
```
when I run paket on the command line I  get

```
c:\dev\FsLab Journal8\FsLab Journal8>.\.paket\paket.exe restore --references-files
Paket version 0.25.1.0
found: c:\dev\FsLab Journal8\FsLab Journal8\paket.dependencies
0 seconds - ready.

```

**Comment by tpetricek** [comment]
Thanks for looking into this - there is something wrong here!

It looks like the build correctly runs the Paket bootstrap to download Paket, but then it fails (for some reason) when running it. Could you try fiddling with the `fsproj` file to see what needs to be changed?

The project contains the "targets" file for Paket [here](https://github.com/tpetricek/FsLab/blob/master/src/journal/FsLab.Journal.fsproj#L387), although there are a few differences from the standard one in Paket. Perhaps @forki can have a look if there is something wrong?

(I couldn't quite get it to work with a full path [here](https://github.com/tpetricek/FsLab/blob/master/src/journal/FsLab.Journal.fsproj#L364) so perhaps the relative path is a problem? Paket has [this instead](https://github.com/fsprojects/Paket/blob/master/.paket/paket.targets#L13)...).

**Comment by TonyAbell** [comment]
found the issue... the paket.lock file was out of date

Updating paket.lock to below.  Fixes the build errors.

```
NUGET
  remote: https://nuget.org/api/v2
  specs:
    Deedle (1.0.7)
    Deedle.RPlugin (1.0.7)
      Deedle (>= 1.0.7)
      R.NET.Community (>= 1.5.16)
      R.NET.Community.FSharp (>= 0.1.9)
      RProvider (>= 1.1.8)
    DotNetZip (1.9.3)
    FAKE (3.14.7)
    Foogle.Charts (0.0.4)
    FSharp.Charting (0.90.9)
    FSharp.Compiler.Service (0.0.82)
    FSharp.Core (3.1.2.1)
    FSharp.Data (2.1.1)
      Zlib.Portable (>= 1.10.0)
    FSharp.Formatting (2.6.3)
      FSharp.Compiler.Service (>= 0.0.81)
	FsLab (0.1.3)
      Deedle (1.0.7)
      Deedle.RPlugin (1.0.7)
      FSharp.Charting (0.90.9)
      FSharp.Data (2.1.1)
      Foogle.Charts (0.0.4)
      MathNet.Numerics (3.5.0)
      MathNet.Numerics.FSharp (3.5.0)
      R.NET.Community (1.5.16)
      R.NET.Community.FSharp (0.1.9)
      RProvider (1.1.8)
    FsLab.Runner (0.1.3)
      Deedle (1.0.7)
      Deedle.RPlugin (1.0.7)
      FSharp.Charting (0.90.9)
      FSharp.Compiler.Service (0.0.82)
      FSharp.Data (2.1.1)
      FSharp.Formatting (2.6.3)
      Foogle.Charts (0.0.4)
      MathNet.Numerics (3.5.0)
      MathNet.Numerics.FSharp (3.5.0)
      Microsoft.AspNet.Razor (3.2.2)
      R.NET.Community (1.5.16)
      R.NET.Community.FSharp (0.1.9)
      RProvider (1.1.8)
      RazorEngine (3.4.2)
    MathNet.Numerics (3.5.0)
      TaskParallelLibrary (>= 1.0.2856) - >= net35 < net40
    MathNet.Numerics.FSharp (3.5.0)
      FSharp.Core (>= 3.1.2.1)
      MathNet.Numerics (3.5.0)
	Microsoft.AspNet.Razor (3.2.2)
    Newtonsoft.Json (6.0.8)
    NuGet.CommandLine (2.8.3)
    Paket.Core (0.24.3)
      DotNetZip (>= 1.9.3)
      FSharp.Core (>= 3.1.2.1)
      Newtonsoft.Json (>= 6.0.8)
    R.NET.Community (1.5.16)
    R.NET.Community.FSharp (0.1.9)
      R.NET.Community (>= 1.5.16)
	RazorEngine (3.4.2)
      Microsoft.AspNet.Razor (>= 3.0.0)
    RProvider (1.1.8)
      R.NET.Community (1.5.16)
      R.NET.Community.FSharp (0.1.9)
    TaskParallelLibrary (1.0.2856.0) - >= net35 < net40
    Zlib.Portable (1.10.0)
```

**Comment by TonyAbell** [comment]
Better yet, removing 

```
Microsoft.AspNet.Razor
RazorEngine
```
from [here](https://github.com/tpetricek/FsLab/blob/master/src/journal/paket.references.template#L15-L16)  is more appropriate

**Comment by tpetricek** [comment]
Thanks for looking into this - the two lines were certainly an error (not sure why it worked for me... :confused:)  
I [uploaded the updated template to VS gallery](https://visualstudiogallery.msdn.microsoft.com/45373b36-2a4c-4b6a-b427-93c7a8effddb). Please check it and let me know if it fixed the problem!

**Comment by tpetricek** [comment]
BTW: The `paket.lock` file that we are [generating here](https://github.com/tpetricek/FsLab/blob/master/build.fsx#L199) is still a bit wrong - because it does not list all the dependencies under `FsLab` and `FsLab.Runner` (the one you posted above does that). Though Paket does not seem to mind that. But I guess we could fix it.

**Comment by TonyAbell** [comment]
I installed FsLab from the VS gallery, and verified that everything is working.

**Comment by tpetricek** [comment]
Wooohoo, thanks for debugging this :-)
