### ISSUE TITLE
For html output make the code collapsed by default

### ISSUE THREAD

**Issue by damageboy** [tpetricek/FsLab#77]
When outputing a jourmal with text/charts it does make sense to keep the code available for inspection etc. in the generated output, but long pieces of code distract the reader of the notebook.

It is very important to keep the code around, tool-tips and all, but it would make more sense to collapse it by default with jquery (which is clearly already referenced by the template), something like 
[accordion](http://jqueryui.com/accordion/#collapsible) should do the trick...?

Any objections to something like this?

**Comment by TonyAbell** [comment]
It would be nice to be able to set this option in the mark up, not a global default.

**Comment by damageboy** [comment]
I agree, any requests, how should this be marked?
Today there's support for:
```
(*** hide ***)
```

Would something like:
```
(*** collapse ***)
```

be ok?

**Comment by TonyAbell** [comment]
that works

**Comment by tpetricek** [comment]
(*** collapse ***)

sounds reasonable. You can kind of do this with the `(*[omit:...]*)....(*[/omit]*)` tag but that will show the omitted code in a tool tip and you cannot copy it from there. See [this example](http://fssnip.net/pt).

No matter what we do, this is a change for [F# Formatting](https://github.com/tpetricek/FSharp.Formatting/). I think that something that would unify the `omit` tag with a `collapse` command that you suggest would be nice.

(Both could show in a way similar to the `omit` tag on F# Snippets, but both should be expandable to see the original code in a copy-and-paste-able format)

**Comment by tpetricek** [comment]
Closing the issue here - please move it to F# Formatting.

**Comment by damageboy** [comment]
Oops, I was sure that `(*** hide ***)` was a FsLab custom thing, will move on to there...
